/****** Object:  Table [dbo].[T_AlarmTrack]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_AlarmTrack](
	[AlarmTrackID] [int] IDENTITY(1,1) NOT NULL,
	[Task] [nvarchar](max) NULL,
	[TrackTime] [datetime2](7) NULL,
	[UserID] [nvarchar](50) NULL,
	[AlarmID] [int] NULL,
	[AlarmSiteID] [int] NULL,
 CONSTRAINT [PK_AlarmTrack] PRIMARY KEY CLUSTERED 
(
	[AlarmTrackID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_AlarmTrack] ON [dbo].[T_AlarmTrack]
(
	[AlarmID] ASC,
	[AlarmSiteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[T_AlarmTrack]  WITH CHECK ADD  CONSTRAINT [FK_AlarmTrack] FOREIGN KEY([AlarmID], [AlarmSiteID])
REFERENCES [dbo].[T_Alarms] ([AlarmID], [AlarmSiteID])
ALTER TABLE [dbo].[T_AlarmTrack] CHECK CONSTRAINT [FK_AlarmTrack]