/****** Object:  Table [dbo].[T_AlarmComments]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_AlarmComments](
	[AlarmCommentID] [int] IDENTITY(1,1) NOT NULL,
	[CommentID] [int] NULL,
	[AlarmID] [int] NULL,
	[AlarmSiteID] [int] NULL,
 CONSTRAINT [PK_AlarmComments] PRIMARY KEY CLUSTERED 
(
	[AlarmCommentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_AlarmID] ON [dbo].[T_AlarmComments]
(
	[AlarmID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_CommentID] ON [dbo].[T_AlarmComments]
(
	[CommentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IXAlarmID] ON [dbo].[T_AlarmComments]
(
	[AlarmID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[T_AlarmComments]  WITH CHECK ADD  CONSTRAINT [FK_Alarms] FOREIGN KEY([AlarmID], [AlarmSiteID])
REFERENCES [dbo].[T_Alarms] ([AlarmID], [AlarmSiteID])
ALTER TABLE [dbo].[T_AlarmComments] CHECK CONSTRAINT [FK_Alarms]
ALTER TABLE [dbo].[T_AlarmComments]  WITH CHECK ADD  CONSTRAINT [FK_Comments] FOREIGN KEY([CommentID])
REFERENCES [dbo].[T_Comments] ([CommentID])
ALTER TABLE [dbo].[T_AlarmComments] CHECK CONSTRAINT [FK_Comments]