/****** Object:  Table [dbo].[T_AlarmCADStatus]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_AlarmCADStatus](
	[AlarmCADStatusID] [int] IDENTITY(1,1) NOT NULL,
	[User] [nvarchar](50) NULL,
	[Creation_Date] [datetime] NULL,
	[AlarmID] [int] NULL,
	[AlarmSiteID] [int] NULL,
	[CADStatusID] [int] NULL,
 CONSTRAINT [PK_AlarmCADStatus] PRIMARY KEY CLUSTERED 
(
	[AlarmCADStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_Alarm_AlarmCADStatus] ON [dbo].[T_AlarmCADStatus]
(
	[AlarmID] ASC,
	[AlarmSiteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_CADStatusAlarm] ON [dbo].[T_AlarmCADStatus]
(
	[CADStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[T_AlarmCADStatus]  WITH CHECK ADD  CONSTRAINT [FK_Alarms_AlarmCADStatus] FOREIGN KEY([AlarmID], [AlarmSiteID])
REFERENCES [dbo].[T_Alarms] ([AlarmID], [AlarmSiteID])
ALTER TABLE [dbo].[T_AlarmCADStatus] CHECK CONSTRAINT [FK_Alarms_AlarmCADStatus]
ALTER TABLE [dbo].[T_AlarmCADStatus]  WITH CHECK ADD  CONSTRAINT [FK_CADStatus_AlarmCADStatus] FOREIGN KEY([CADStatusID])
REFERENCES [dbo].[LT_CADStatus] ([CADStatusID])
ALTER TABLE [dbo].[T_AlarmCADStatus] CHECK CONSTRAINT [FK_CADStatus_AlarmCADStatus]