/****** Object:  Table [dbo].[T_AllScenarios]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_AllScenarios](
	[RegionTitle1] [nvarchar](200) NULL,
	[CityTitle1] [nvarchar](200) NULL,
	[StationTitle1] [nvarchar](200) NULL,
	[LevelTitle1] [nvarchar](200) NULL,
	[ZoneTitle1] [nvarchar](200) NULL,
	[TouchPointTitle1] [nvarchar](200) NULL,
	[EventDefinitionTitle1] [nvarchar](200) NOT NULL,
	[EventID] [int] NOT NULL,
	[EventSiteID] [int] NOT NULL,
	[AlarmID] [int] NOT NULL,
	[AlarmSiteID] [int] NOT NULL,
	[EventAlarms] [int] NOT NULL,
	[EventAlarms_EventSiteID] [int] NOT NULL,
	[Alarms_AlarmID] [int] NOT NULL,
	[Alarms_AlarmSiteID] [int] NOT NULL,
	[AlarmCode] [nvarchar](200) NULL,
	[Occurance_Date] [datetime] NULL,
	[Response_User] [nvarchar](200) NULL,
	[Response_Date] [datetime] NULL,
	[AlarmStatusID] [int] NOT NULL,
	[AlarmClassificationID] [int] NOT NULL,
	[AlarmsDefinitionID] [int] NOT NULL,
	[AlarmDefinitionSiteID] [int] NOT NULL,
	[EscalationLevelID] [int] NOT NULL,
	[EscalationLevelSiteID] [int] NOT NULL,
	[ResponseTimeDifference] [int] NULL,
	[EscalationDescription] [nvarchar](4000) NULL,
	[EscalationUser] [nvarchar](200) NULL,
	[EscalationDate] [datetime] NULL,
	[AlarmComment] [nvarchar](4000) NULL,
	[AlarmDefinitionTitle1] [nvarchar](200) NULL,
	[AlarmStatusTitle1] [nvarchar](200) NULL,
	[AlarmClassificationTitle1] [nvarchar](200) NULL,
	[ScenarioTitle1] [nvarchar](200) NULL,
	[ScenarioImpact] [int] NOT NULL,
	[AlarmScenarioID] [int] NOT NULL,
	[AlarmScenarios_AlarmID] [int] NOT NULL,
	[AlarmScenarios_AlarmSiteID] [int] NOT NULL,
	[ScenarioID] [int] NOT NULL,
	[ScenarioSiteID] [int] NOT NULL,
	[IsSelected] [bit] NULL,
	[SelectedCreationDate] [datetime] NULL,
	[SelectedUser] [nvarchar](100) NULL
) ON [PRIMARY]