/****** Object:  Table [dbo].[T_MapFile]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_MapFile](
	[MapFileID] [int] IDENTITY(1,1) NOT NULL,
	[FileData] [varbinary](max) NULL,
	[Name] [nvarchar](100) NULL,
 CONSTRAINT [PK_MapFile] PRIMARY KEY CLUSTERED 
(
	[MapFileID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]