/****** Object:  Table [dbo].[T_Role]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[T_Role](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](50) NULL,
	[RoleTypeID] [int] NULL,
	[StateID] [int] NULL,
	[RoleDescription] [nvarchar](100) NULL,
	[RoleCode] [nvarchar](50) NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_RoleType] ON [dbo].[T_Role]
(
	[RoleTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[T_Role]  WITH CHECK ADD  CONSTRAINT [FK_RoleState] FOREIGN KEY([StateID])
REFERENCES [dbo].[LT_State] ([StateID])
ALTER TABLE [dbo].[T_Role] CHECK CONSTRAINT [FK_RoleState]
ALTER TABLE [dbo].[T_Role]  WITH CHECK ADD  CONSTRAINT [FK_RoleType] FOREIGN KEY([RoleTypeID])
REFERENCES [dbo].[LT_RoleType] ([RoleTypeID])
ALTER TABLE [dbo].[T_Role] CHECK CONSTRAINT [FK_RoleType]